var config = {
    rules: {
        // These are the fields we check for duplicates
        duplicates: ["name", "branch", "address1", "address2", "city", "state", "zip", "country", "region code", "misc 1", "misc 2", "redirectclientid", "violationpackageid", "custom field 1", "custom field 2", "custom field 3", "custom field 4", "custom field 5", "custom field 6"],

        //! These are rules for bad characters we don't want 👈
        badchars: {
            "preceding comma": /^\s*,/, // No comma at the start
            "ending comma": /,\s*$/, // No comma at the end
            "ending hyphen": /-\s*$/, // No hyphen at the end
            "preceding hyphen": /^\s*-/, // No hyphen at the start
            "double quote": "\"", // No double quotes
            "semi-colon": ";" // No semi-colons
        },

       // A list of countries we can't include in our data
        sanctionedCountries: [
            "Cuba",
			"CUB",
            "Iran",
            "Iran (Islamic Republic of)",
            "Iran, Islamic Republic of",
			"IRN",
            "Islamic Republic of Iran",
            "North Korea",
            "Korea (North)",
            "Korea North",
            "Korea, DPR",
            "Korea, Dem. People's Rep of",
            "Korea, Dem. People's Rep. of",
            "Korea, Democratic People's Republic of",
            "Korea, North",
            "North Korea (Democratic People's Republic)",
			"PRK",
            "Syria",
            "Syrian Arab Republic (Syria)",
            "Syrian Arab Republic",
			"SYR",
        ],

        // Rules for how to write addresses properly
        address1: {
			// Different ways people might write the same thing
            variations: {
                // These are different ways people might write "drive"
                " drive ": /\s+drive+\s/,
                " DRIVE ": /\s+DRIVE+\s/,
                " Drive ": /\s+Drive+\s/,
                " drive ": /\s+drive/,
                " DRIVE ": /\s+DRIVE/,
                " Drive ": /\s+Drive/,
                " Dr. ": /\s+Dr\.+\s/,
                " dr. ": /\s+dr\.+\s/,
                " DR. ": /\s+DR\.+\s/,
                " Dr, ": /\s+Dr\,+\s/,
                " dr, ": /\s+dr\,+\s/,
                " DR, ": /\s+DR\,+\s/,
                " DR ": /\s+DR+\s/,
                " Dr ": /\s+Dr+\s/,
                // These are different ways people might write "road"
                " road ": /\s+road+\s/,
                " ROAD ": /\s+ROAD+\s/,
                " Road ": /\s+Road+\s/,
                " road ": /\s+road/,
                " ROAD ": /\s+ROAD/,
                " Road ": /\s+Road/,
                " rd. ": /\s+rd\.+\s/,
                " Rd. ": /\s+Rd\.+\s/,
                " RD. ": /\s+RD\.+\s/,
                " rd, ": /\s+rd\,+\s/,
                " Rd, ": /\s+Rd\,+\s/,
                " RD, ": /\s+RD\,+\s/,
                " RD ": /\s+RD+\s/,
                " Rd ": /\s+Rd+\s/
            },
			 // Short versions of words and their full versions
            abbreviations: {
                // These are abbreviations for "road"
                "rd": "Road",
                "rd.": "Road",
                "Rd": "Road",
                "Rd.": "Road",
                "RD.": "Road",
                "RD": "Road"
            }
        },

        // Rules for writing city names correctly
        city: {
            variations: {
               // Different ways people write "north" in city names
                " north ": /\s+north+\s/,
                " NORTH ": /\s+NORTH+\s/,
                " North ": /\s+North+\s/,
                "north ": /north+\s/,
                "NORTH ": /NORTH+\s/,
                "North ": /North+\s/,
                "N. ": /^N\.+\s/,
                "N ": /^N+\s/,
                " N ": /\s+N+\s/,
                // These are different ways people might write "saint"
                " SAINT ": /\s+SAINT+\s/,
                "SAINT ": /SAINT+\s/,
                "Saint ": /Saint+\s/,
                "saint ": /saint+\s/,
                " Saint ": /\s+Saint+\s/,
                " saint ": /\s+saint+\s/,
                " st ": /\s+st+\s/,
                " St ": /\s+St+\s/,
                " ST ": /\s+ST+\s/,
                "Saint ": /Saint+\s/,
                "ST. ": /^ST\.+\s/,
                "ST, ": /^ST\,+\s/,
                "ST ": /^ST+\s/,
                "St.": /^St\.+\s/,
                "St,": /^St\,+\s/,
                "St ": /^St+\s/,
                "st ": /^st+\s/,
                "st.": /^st\.+\s/,
                "st,": /^st\,+\s/,
                // These are different ways people might write "fort"
                "fort ": /^fort+\s/,
                " fort ": /\s+fort+\s/,
                " ft ": /\s+ft+\s/,
                " Ft ": /\s+Ft+\s/,
                " FT ": /\s+FT+\s/,
                "Fort ": /^Fort+\s/,
                " FORT ": /\s+FORT+\s/,
                "FORT ": /FORT+\s/,
                "FT ": /^FT+\s/,
                "FT. ": /^FT\.+\s/,
                "Ft. ": /^Ft\.+\s/,
                "Ft ": /^Ft+\s/,
                "ft ": /^ft+\s/,
                "ft. ": /^ft\.+\s/
            },
            abbreviations: {
                // These are abbreviations for "fort" and "saint"
                "ft": "Fort",
                "ft.": "Fort",
                "Ft": "Fort",
                "Ft.": "Fort",
                "St.": "Saint",
                "st.": "Saint",
                "St": "Saint",
                "st": "Saint"
            }
        },

        // These are rules for the "state" field
        state: {
            abbreviations: {
                // These are abbreviations for US states and some other regions
                "AB": "Alberta",
                "AL": "Alabama",
                "AK": "Alaska",
                "AZ": "Arizona",
                "AR": "Arkansas",
                "CA": "California",
                "CO": "Colorado",
                "CT": "Connecticut",
                "DE": "Delaware",
                "FL": "Florida",
                "GA": "Georgia",
                "HI": "Hawaii",
                "ID": "Idaho",
                "IL": "Illinois",
                "IN": "Indiana",
                "IA": "Iowa",
                "KS": "Kansas",
                "KY": "Kentucky",
                "LA": "Louisiana",
                "ME": "Maine",
                "MD": "Maryland",
                "MA": "Massachusetts",
                "MI": "Michigan",
                "MN": "Minnesota",
                "MS": "Mississippi",
                "MO": "Missouri",
                "MT": "Montana",
                "NE": "Nebraska",
                "NV": "Nevada",
                "NH": "New Hampshire",
                "NJ": "New Jersey",
                "NM": "New Mexico",
                "NY": "New York",
                "NC": "North Carolina",
                "ND": "North Dakota",
                "OH": "Ohio",
                "OK": "Oklahoma",
                "OR": "Oregon",
                "PA": "Pennsylvania",
                "RI": "Rhode Island",
                "SC": "South Carolina",
                "SD": "South Dakota",
                "TN": "Tennessee",
                "TX": "Texas",
                "UT": "Utah",
                "VT": "Vermont",
                "VA": "Virginia",
                "WA": "Washington",
                "WV": "West Virginia",
                "WI": "Wisconsin",
                "WY": "Wyoming",
                "ACT": "Australian Capital Territory",
                "JBT": "New South Wales",
                "NSW": "Norfolk Island",
                "NT": "Northern Territory",
                "QLD": "Queensland",
                "SA": "South Australia",
                "TAS": "Tasmania",
                "VIC": "Victoria",
                "WA": "Western Australia"
            },
            inclusions: {
                // These are states and regions we want to include
                "Australian Capital Territory": 1,
                "New South Wales": 1,
                "Norfolk Island": 1,
                "Northern Territory": 1,
                "Queensland": 1,
                "South Australia": 1,
                "Tasmania": 1,
                "Victoria": 1,
                "Western Australia": 1,
                "ACT": 1,
                "JBT": 1,
                "NSW": 1,
                "NT": 1,
                "QLD": 1,
                "SA": 1,
                "TAS": 1,
                "VIC": 1,
                "WA": 1,
                "Beijing": 1,
                "Tianjin": 1,
                "Chongqing": 1,
                "Shanghai": 1,
                "Heilongjiang": 1,
                "Jilin": 1,
                "Liaoning": 1,
                "Qinghai": 1,
                "Gansu": 1,
                "Shaanxi": 1,
                "Shanxi": 1,
                "Hebei": 1,
                "Sichuan": 1,
                "Hubei": 1,
                "Henan": 1,
                "Shandong": 1,
                "Anhui": 1,
                "Jiangsu": 1,
                "Yunnan": 1,
                "Guizhou": 1,
                "Hunan": 1,
                "Jiangxi": 1,
                "Zhejiang": 1,
                "Hainan": 1,
                "Guangdong": 1,
                "Fujian": 1,
                "Ontario": 1,
                "Quebec": 1,
                "Nova Scotia": 1,
                "New Brunswick": 1,
                "Manitoba": 1,
                "British Columbia": 1,
                "Prince Edward Island": 1,
                "Saskatchewan": 1,
                "Alberta": 1,
                "Newfoundland and Labrador": 1,
                "Newfoundland": 1,
                "Ont.": 1,
                "ON": 1,
                "Que., P.Q.": 1,
                "QC": 1,
                "N.S.": 1,
                "NS": 1,
                "N.B.": 1,
                "NB": 1,
                "Man.": 1,
                "MB": 1,
                "B.C.": 1,
                "BC": 1,
                "P.E.I.": 1,
                "PE": 1,
                "Sask.": 1,
                "SK": 1,
                "Alta.": 1,
                "AB": 1,
                "Nfld., Lab.": 1,
                "NL": 1,
                "Alabama": 1,
                "Alaska": 1,
                "Arizona": 1,
                "Arkansas": 1,
                "California": 1,
                "Colorado": 1,
                "Connecticut": 1,
                "Delaware": 1,
                "Florida": 1,
                "Georgia": 1,
                "Hawaii": 1,
                "Idaho": 1,
                "Illinois": 1,
                "Indiana": 1,
                "Iowa": 1,
                "Kansas": 1,
                "Kentucky": 1,
                "Louisiana": 1,
                "Maine": 1,
                "Maryland": 1,
                "Massachusetts": 1,
                "Michigan": 1,
                "Minnesota": 1,
                "Mississippi": 1,
                "Missouri": 1,
                "Montana": 1,
                "Nebraska": 1,
                "Nevada": 1,
                "New Hampshire": 1,
                "New Jersey": 1,
                "New Mexico": 1,
                "New York": 1,
                "North Carolina": 1,
                "North Dakota": 1,
                "Ohio": 1,
                "Oklahoma": 1,
                "Oregon": 1,
                "Pennsylvania": 1,
                "Rhode Island": 1,
                "South Carolina": 1,
                "South Dakota": 1,
                "Tennessee": 1,
                "Texas": 1,
                "Utah": 1,
                "Vermont": 1,
                "Virginia": 1,
                "Washington": 1,
                "West Virginia": 1,
                "Wisconsin": 1,
                "Wyoming": 1,
                "AL": 1,
                "AK": 1,
                "AZ": 1,
                "AR": 1,
                "CA": 1,
                "CO": 1,
                "CT": 1,
                "DE": 1,
                "DC": 1,
                "FL": 1,
                "GA": 1,
                "HI": 1,
                "ID": 1,
                "IL": 1,
                "IN": 1,
                "IA": 1,
                "KS": 1,
                "KY": 1,
                "LA": 1,
                "ME": 1,
                "MD": 1,
                "MA": 1,
                "MI": 1,
                "MN": 1,
                "MS": 1,
                "MO": 1,
                "MT": 1,
                "NE": 1,
                "NV": 1,
                "NH": 1,
                "NJ": 1,
                "NM": 1,
                "NY": 1,
                "NC": 1,
                "ND": 1,
                "OH": 1,
                "OK": 1,
                "OR": 1,
                "PA": 1,
                "RI": 1,
                "SC": 1,
                "SD": 1,
                "TN": 1,
                "TX": 1,
                "UT": 1,
                "VT": 1,
                "VA": 1,
                "WA": 1,
                "WV": 1,
                "WI": 1,
                "WY": 1,
                "AS": 1,
                "GU": 1,
                "MP": 1,
                "PR": 1,
                "VI": 1,
                "GUANAJUATO": 1,
                "QUERÉTARO": 1,
                "AGUASCALIENTES": 1,
                "MICHOACÁN": 1,
                "SAN LUIS POTOSÍ": 1,
                "PUEBLA": 1,
                "TLAXCALA": 1,
                "VERACRUZ": 1,
                "JALISCO": 1,
                "COLIMA": 1,
                "SINALOA": 1,
                "NAYARIT": 1,
                "DISTRITO FEDERAL": 1,
                "ESTADO DE MÉXICO": 1,
                "HIDALGO": 1,
                "GUERRERO": 1,
                "MORELOS": 1,
                "NUEVO LEON": 1,
                "TAMAULIPAS": 1,
                "COAHUILA": 1,
                "TABASCO": 1,
                "CHIAPAS": 1,
                "QUINTANA ROO": 1,
                "CAMPECHE": 1,
                "YUCATÁN": 1
            }
        },

        // These are rules for the "country" field
        country: {
            abbreviations: {
                // These are abbreviations for countries
                "US": "USA",
                "USA": "United States",
                "AFG": "Afghanistan",
                "AHO": "Netherlands Antilles",
                "ALB": "Albania",
                "ALG": "Algeria",
                "AND": "Andorra",
                "ANG": "Angola",
                "ANT": "Antigua and Barbuda",
                "ARG": "Argentina",
                "ARM": "Armenia",
                "ARU": "Aruba",
                "ASA": "American Samoa",
                "AUS": "Australia",
                "AUT": "Austria",
                "AZE": "Azerbaijan",
                "BAH": "Bahamas",
                "BAN": "Bangladesh",
                "BAR": "Barbados",
                "BDI": "Burundi",
                "BEL": "Belgium",
                "BEN": "Benin",
                "BER": "Bermuda",
                "BHU": "Bhutan",
                "BIH": "Bosnia and Herzegovina",
                "BIZ": "Belize",
                "BLR": "Belarus",
                "BOL": "Bolivia",
                "BOT": "Botswana",
                "BRA": "Brazil",
                "BRN": "Bahrain",
                "BRU": "Brunei",
                "BUL": "Bulgaria",
                "BUR": "Burkina Faso",
                "CAF": "Central African Republic",
                "CAM": "Cambodia",
                "CAN": "Canada",
                "CAY": "Cayman Islands",
                "CGO": "Congo",
                "CHA": "Chad",
                "CHI": "Chile",
                "CHN": "China",
                "CIV": "Côte d'Ivoire",
                "CMR": "Cameroon",
                "COD": "DR Congo",
                "COK": "Cook Islands",
                "COL": "Colombia",
                "COM": "Comoros",
                "CPV": "Cape Verde",
				"CRC":"Costa Rica",
				"CRO":"Croatia",
				"CUB":"Cuba",
				"CYP":"Cyprus",
				"CZE":"Czech Republic",
				"DEN":"Denmark",
				"DJI":"Djibouti",
				"DMA":"Dominica",
				"DOM":"Dominican Republic",
				"ECU":"Ecuador",
				"EGY":"Egypt",
				"ERI":"Eritrea",
				"ESA":"El Salvador",
				"ESP":"Spain",
				"EST":"Estonia",
				"ETH":"Ethiopia",
				"FIJ":"Fiji",
				"FIN":"Finland",
				"FRA":"France",
				"FSM":"Micronesia",
				"GAB":"Gabon",
				"GAM":"Gambia",
				"GBR":"Great Britain",
				"GBS":"Guinea-Bissau",
				"GEO":"Georgia",
				"GEQ":"Equatorial Guinea",
				"GER":"Germany",
				"GHA":"Ghana",
				"GRE":"Greece",
				"GRN":"Grenada",
				"GUA":"Guatemala",
				"GUI":"Guinea",
				"GUM":"Guam",
				"GUY":"Guyana",
				"HAI":"Haiti",
				"HKG":"Hong Kong",
				"HON":"Honduras",
				"HUN":"Hungary",
				"INA":"Indonesia",
				"IND":"India",
				"IRI":"Iran",
				"IRL":"Ireland",
				"IRQ":"Iraq",
				"ISL":"Iceland",
				"ISR":"Israel",
				"ISV":"Virgin Islands",
				"ITA":"Italy",
				"IVB":"British Virgin Islands",
				"JAM":"Jamaica",
				"JOR":"Jordan",
				"JPN":"Japan",
				"KAZ":"Kazakhstan",
				"KEN":"Kenya",
				"KGZ":"Kyrgyzstan",
				"KIR":"Kiribati",
				"KOR":"South Korea",
				"KSA":"Saudi Arabia",
				"KUW":"Kuwait",
				"LAO":"Laos",
				"LAT":"Latvia",
				"LBA":"Libya",
				"LBR":"Liberia",
				"LCA":"Saint Lucia",
				"LES":"Lesotho",
				"LIB":"Lebanon",
				"LIE":"Liechtenstein",
				"LTU":"Lithuania",
				"LUX":"Luxembourg",
				"MAD":"Madagascar",
				"MAR":"Morocco",
				"MAS":"Malaysia",
				"MAW":"Malawi",
				"MDA":"Moldova",
				"MDV":"Maldives",
				"MEX":"Mexico",
				"MGL":"Mongolia",
				"MHL":"Marshall Islands",
				"MKD":"Macedonia",
				"MLI":"Mali",
				"MLT":"Malta",
				"MNE":"Montenegro",
				"MON":"Monaco",
				"MOZ":"Mozambique",
				"MRI":"Mauritius",
				"MTN":"Mauritania",
				"MYA":"Myanmar",
				"NAM":"Namibia",
				"NCA":"Nicaragua",
				"NED":"Netherlands",
				"NEP":"Nepal",
				"NGR":"Nigeria",
				"NIG":"Niger",
				"NOR":"Norway",
				"NRU":"Nauru",
				"NZL":"New Zealand",
				"OMA":"Oman",
				"PAK":"Pakistan",
				"PAN":"Panama",
				"PAR":"Paraguay",
				"PER":"Peru",
				"PHI":"Philippines",
				"PLE":"Palestine",
				"PLW":"Palau",
				"PNG":"Papua New Guinea",
				"POL":"Poland",
				"POR":"Portugal",
				"PRK":"North Korea",
				"PUR":"Puerto Rico",
				"QAT":"Qatar",
				"ROU":"Romania",
				"RSA":"South Africa",
				"RUS":"Russia",
				"RWA":"Rwanda",
				"SAM":"Samoa",
				"SEN":"Senegal",
				"SEY":"Seychelles",
				"SIN":"Singapore",
				"SKN":"Saint Kitts and Nevis",
				"SLE":"Sierra Leone",
				"SLO":"Slovenia",
				"SMR":"San Marino",
				"SOL":"Solomon Islands",
				"SOM":"Somalia",
				"SRB":"Serbia",
				"SRI":"Sri Lanka",
				"STP":"São Tomé and Príncipe",
				"SUD":"Sudan",
				"SUI":"Switzerland",
				"SUR":"Suriname",
				"SVK":"Slovakia",
				"SWE":"Sweden",
				"SWZ":"Swaziland",
				"SYR":"Syria",
				"TAN":"Tanzania",
				"TGA":"Tonga",
				"THA":"Thailand",
				"TJK":"Tajikistan",
				"TKM":"Turkmenistan",
				"TLS":"Timor-Leste",
				"TOG":"Togo",
				"TPE":"Chinese Taipei[3]",
				"TRI":"Trinidad and Tobago",
				"TUN":"Tunisia",
				"TUR":"Turkey",
				"TUV":"Tuvalu",
				"UAE":"United Arab Emirates",
				"UGA":"Uganda",
				"UKR":"Ukraine",
				"URU":"Uruguay",
				"USA":"United States",
				"UZB":"Uzbekistan",
				"VAN":"Vanuatu",
				"VEN":"Venezuela",
				"VIE":"Vietnam",
				"VIN":"Saint Vincent and the Grenadines",
				"YEM":"Yemen",
				"ZAM":"Zambia",
				"ZIM":"Zimbabwe"
			},	
			inclusions:{				
					"Afghanistan":1,
					"Africa":1,
					"Albania":1,
					"Algeria":1,
					"American Samoa":1,
					"Andorra":1,
					"Angola":1,
					"Anguilla":1,
					"Antarctica":1,
					"Antigua":1,
					"Argentina":1,
					"Armenia":1,
					"Aruba":1,
					"Ascension Island":1,
					"Australia":1,
					"Austria":1,
					"Azerbaijan":1,
					"Bahamas":1,
					"Bahrain":1,
					"Bangladesh":1,
					"Barbados":1,
					"Belarus":1,
					"Belgium":1,
					"Belize":1,
					"Benin":1,
					"Bermuda":1,
					"Bhutan":1,
					"Bolivia":1,
					"Bosnia":1,
					"Botswana":1,
					"Bouvet Island":1,
					"Brazil":1,
					"British Virgin Islands":1,
					"Brunei":1,
					"Bulgaria":1,
					"Burkina Faso":1,
					"Burma":1,
					"Burundi":1,
					"Cambodia":1,
					"Cameroon":1,
					"Canada":1,
					"Cape Verde Islands":1,
					"Carriacou":1,
					"Cayman Islands":1,
					"Central African Republic":1,
					"Central America":1,
					"Chad":1,
					"Chile":1,
					"China":1,
					"Christmas Islands":1,
					"Cocos Island":1,
					"Colombia":1,
					"Comoros":1,
					"Congo":1,
					"Cook Islands":1,
					"Costa Rica":1,
					"Croatia":1,
					"Cuba":1,
					"Curacao":1,
					"Cyprus":1,
					"Czech Republic":1,
					"Denmark":1,
					"Diego Garcia":1,
					"Djibouti":1,
					"Dominica":1,
					"Dominican Republic":1,
					"East Timor":1,
					"Easter Island":1,
					"Ecuador":1,
					"Egypt":1,
					"El Salvador":1,
					"Equatorial Guinea":1,
					"Eritrea":1,
					"Estonia":1,
					"Ethiopia":1,
					"Faeroe Islands":1,
					"Falkland Islands":1,
					"Fiji":1,
					"Finland":1,
					"France":1,
					"French Antilles":1,
					"French Guiana":1,
					"French Polynesia":1,
					"Gabon":1,
					"Gambia":1,
					"Georgia":1,
					"Germany":1,
					"Ghana":1,
					"Gibraltar":1,
					"Greece":1,
					"Greenland":1,
					"Grenada":1,
					"Guadeloupe":1,
					"Guam":1,
					"Guantanamo Bay":1,
					"Guatemala":1,
					"Guernsey":1,
					"Guinea":1,
					"Guinea-Bissau":1,
					"Guyana":1,
					"Haiti":1,
					"Honduras":1,
					"Hong Kong":1,
					"Hungary":1,
					"Iceland":1,
					"India":1,
					"Indonesia":1,
					"Iran":1,
					"Iraq":1,
					"Ireland":1,
					"Isle of Man":1,
					"Israel":1,
					"Italy":1,
					"Ivory Coast":1,
					"Jamaica":1,
					"Japan":1,
					"Jersey":1,
					"Jordan":1,
					"Kazakhstan":1,
					"Kyrgyzstan":1,
					"Kenya":1,
					"Kiribati":1,
					"Korea (North)":1,
					"Korea (South)":1,
					"Kosovo":1,
					"Kuwait":1,
					"Kyrgyzstan":1,
					"Laos":1,
					"Lao People's Democratic Republic":1,
					"Latvia":1,
					"Lebanon":1,
					"Lesotho":1,
					"Liberia":1,
					"Libya":1,
					"Liechtenstein":1,
					"Lithuania":1,
					"Luxembourg":1,
					"Macau":1,
					"Macedonia":1,
					"Madagascar":1,
					"Malawi":1,
					"Malaysia":1,
					"Maldives":1,
					"Mali":1,
					"Malta":1,
					"Marshall Islands":1,
					"Martinique (French)":1,
					"Mauritania":1,
					"Mauritius":1,
					"Mayotte Island":1,
					"Mexico":1,
					"Micronesia":1,
					"Moldova":1,
					"Monaco":1,
					"Mongolia":1,
					"Montenegro":1,
					"Montserrat":1,
					"Morocco":1,
					"Mozambique":1,
					"Myanmar":1,
					"Namibia":1,
					"Nauru":1,
					"Nepal":1,
					"Netherlands":1,
					"Netherlands Antilles":1,
					"Nevis":1,
					"New Caledonia":1,
					"New Zealand":1,
					"Nicaragua":1,
					"Niger":1,
					"Nigeria":1,
					"Niue":1,
					"Norfolk Island":1,
					"North Korea":1,
					"Northern Mariana Islands":1,
					"Norway":1,
					"Oman":1,
					"Pago Pago":1,
					"Pakistan":1,
					"Palau":1,
					"Panama":1,
					"Papua New Guinea":1,
					"Paraguay":1,
					"Peru":1,
					"Philippines":1,
					"Pitcairn Island":1,
					"Poland":1,
					"Polynesia (French)":1,
					"Portugal":1,
					"Puerto Rico":1,
					"Qatar":1,
					"Reunion Island":1,
					"Romania":1,
					"Russia":1,
					"Rwanda":1,
					"S. Georgia & S. Sandwich Isls.":1,
					"Saba":1,
					"Saint Helena":1,
					"Saipan":1,
					"Samoa":1,
					"San Marino":1,
					"Sao Tome":1,
					"Saudi Arabia":1,
					"Scotland":1,
					"Senegal":1,
					"Serbia":1,
					"Serbia and Montenegro":1,
					"Seychelles Islands":1,
					"Sierra Leone":1,
					"Singapore":1,
					"Slovakia":1,
					"Slovenia":1,
					"Solomon Islands":1,
					"Somalia Republic":1,
					"South Africa":1,
					"Somalia":1,
					"South Korea":1,
					"Spain":1,
					"Spanish Sahara":1,
					"Sri Lanka":1,
					"St. Barthelemy":1,
					"St. Eustatius":1,
					"St. Helena":1,
					"St. Kitts/Nevis":1,
					"St. Maarten":1,
					"St. Martin":1,
					"St. Pierre and Miquelon":1,
					"St. Vincent":1,
					"Sudan":1,
					"Suriname":1,
					"Svalbard and Jan Mayen Islands":1,
					"Swaziland":1,
					"Sweden":1,
					"Switzerland":1,
					"Syria":1,
					"Taiwan":1,
					"Tajikistan":1,
					"Tanzania":1,
					"Thailand":1,
					"Togo":1,
					"Tokelau":1,
					"Tonga Island":1,
					"Trinidad and Tobago":1,
					"Tunisia":1,
					"Turkey":1,
					"Turkmenistan":1,
					"Turks and Caicos":1,
					"Tuvalu":1,
					"Uganda":1,
					"Ukraine":1,
					"United Arab Emirates":1,
					"United Kingdom":1,
					"United States":1,
					"Uruguay":1,
					"US Virgin Islands":1,
					"Uzbekistan":1,
					"Vanuatu":1,
					"Vatican City":1,
					"Venezuela":1,
					"Vietnam":1,
					"Wallis and Futuna Islands":1,
					"Western Sahara":1,
					"Western Samoa":1,
					"Yemen":1,
					"Yugoslavia":1,
					"Zaire":1,
					"Zambia":1,
					"Zimbabwe":1,
					"AFG":1,
					"AHO":1,
					"ALB":1,
					"ALG":1,
					"AND":1,
					"ANG":1,
					"ANT":1,
					"ARG":1,
					"ARM":1,
					"ARU":1,
					"ASA":1,
					"AUS":1,
					"AUT":1,
					"AZE":1,
					"BAH":1,
					"BAN":1,
					"BAR":1,
					"BDI":1,
					"BEL":1,
					"BEN":1,
					"BER":1,
					"BHU":1,
					"BIH":1,
					"BIZ":1,
					"BLR":1,
					"BOL":1,
					"BOT":1,
					"BRA":1,
					"BRN":1,
					"BRU":1,
					"BUL":1,
					"BUR":1,
					"CAF":1,
					"CAM":1,
					"CAN":1,
					"CAY":1,
					"CGO":1,
					"CHA":1,
					"CHI":1,
					"CHN":1,
					"CIV":1,
					"CMR":1,
					"COD":1,
					"COK":1,
					"COL":1,
					"COM":1,
					"CPV":1,
					"CRC":1,
					"CRO":1,
					"CUB":1,
					"CYP":1,
					"CZE":1,
					"DEN":1,
					"DJI":1,
					"DMA":1,
					"DOM":1,
					"ECU":1,
					"EGY":1,
					"ERI":1,
					"ESA":1,
					"ESP":1,
					"EST":1,
					"ETH":1,
					"FIJ":1,
					"FIN":1,
					"FRA":1,
					"FSM":1,
					"GAB":1,
					"GAM":1,
					"GBR":1,
					"GBS":1,
					"GEO":1,
					"GEQ":1,
					"GER":1,
					"GHA":1,
					"GRE":1,
					"GRN":1,
					"GUA":1,
					"GUI":1,
					"GUM":1,
					"GUY":1,
					"HAI":1,
					"HKG":1,
					"HON":1,
					"HUN":1,
					"INA":1,
					"IND":1,
					"IRI":1,
					"IRL":1,
					"IRQ":1,
					"ISL":1,
					"ISR":1,
					"ISV":1,
					"ITA":1,
					"IVB":1,
					"JAM":1,
					"JOR":1,
					"JPN":1,
					"KAZ":1,
					"KEN":1,
					"KGZ":1,
					"KIR":1,
					"KOR":1,
					"KSA":1,
					"KUW":1,
					"LAO":1,
					"LAT":1,
					"LBA":1,
					"LBR":1,
					"LCA":1,
					"LES":1,
					"LIB":1,
					"LIE":1,
					"LTU":1,
					"LUX":1,
					"MAD":1,
					"MAR":1,
					"MAS":1,
					"MAW":1,
					"MDA":1,
					"MDV":1,
					"MEX":1,
					"MGL":1,
					"MHL":1,
					"MKD":1,
					"MLI":1,
					"MLT":1,
					"MNE":1,
					"MON":1,
					"MOZ":1,
					"MRI":1,
					"MTN":1,
					"MYA":1,
					"NAM":1,
					"NCA":1,
					"NED":1,
					"NEP":1,
					"NGR":1,
					"NIG":1,
					"NOR":1,
					"NRU":1,
					"NZL":1,
					"OMA":1,
					"PAK":1,
					"PAN":1,
					"PAR":1,
					"PER":1,
					"PHI":1,
					"PLE":1,
					"PLW":1,
					"PNG":1,
					"POL":1,
					"POR":1,
					"PRK":1,
					"PUR":1,
					"QAT":1,
					"ROU":1,
					"RSA":1,
					"RUS":1,
					"RWA":1,
					"SAM":1,
					"SEN":1,
					"SEY":1,
					"SIN":1,
					"SKN":1,
					"SLE":1,
					"SLO":1,
					"SMR":1,
					"SOL":1,
					"SOM":1,
					"SRB":1,
					"SRI":1,
					"STP":1,
					"SUD":1,
					"SUI":1,
					"SUR":1,
					"SVK":1,
					"SWE":1,
					"SWZ":1,
					"SYR":1,
					"TAN":1,
					"TGA":1,
					"THA":1,
					"TJK":1,
					"TKM":1,
					"TLS":1,
					"TOG":1,
					"TPE":1,
					"TRI":1,
					"TUN":1,
					"TUR":1,
					"TUV":1,
					"UAE":1,
					"UGA":1,
					"UK":1,
					"UKR":1,
					"URU":1,
					"US":1,
					"USA":1,
					"UZB":1,
					"VAN":1,
					"VEN":1,
					"VIE":1,
					"VIN":1,
					"YEM":1,
					"ZAM":1,
					"ZIM":1
			}
		}
		
	}

};